ProjetoArquivo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

cadastros/urls.py
from django.urls import path
from .views import FuncionarioCreate, MovimentacaoCreate
from .views import FuncionarioUpdate, MovimentacaoUpdate
from .views import FuncionarioDelete, MovimentacaoDelete
from .views import FuncionarioList, MovimentacaoList, FuncionarioDeleteList

urlpatterns = [
    path('cadastrar/funcionario/', FuncionarioCreate.as_view(), name="cadastrar-funcionario"),
    path('cadastrar/movimentacao/', MovimentacaoCreate.as_view(), name="cadastrar-movimentacao"),
    
    path('editar/funcionario/<int:pk>/', FuncionarioUpdate.as_view(), name="editar-funcionario"),
    path('editar/movimentacao/<int:pk>/', MovimentacaoUpdate.as_view(), name="editar-movimentacao"),
    
    path('excluir/funcionario/<int:pk>/', FuncionarioDelete.as_view(), name="excluir-funcionario"),
    path('excluir/movimentacao/<int:pk>/', MovimentacaoDelete.as_view(), name="excluir-movimentacao"),
    
    path('', FuncionarioList.as_view(), name="listar-funcionario"),
    path('listar/movimentacao/', MovimentacaoList.as_view(), name="listar-movimentacao"),
    
    path('listar/funcionario/delete', FuncionarioDeleteList.as_view(), name="listar-funcionario-delete"),
]

paginas/urls.py
from django.urls import path


urlpatterns = [
   
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='usuarios/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

cadastros/models.py
from django.db import models
import datetime

# Create your models here.
class Funcionario(models.Model):
    VINCULO_CHOICES = (
        ('C', 'Comissionado'),
        ('CO', 'Contratado'),
        ('CN', 'Concursado'),
    )

    nome = models.CharField(max_length=50)
    matricula = models.CharField(max_length=6, verbose_name="Matrícula")
    cpf = models.IntegerField(verbose_name="CPF", max_length=11)
    vinculo = models.CharField(max_length=12, verbose_name="Vínculo", choices=VINCULO_CHOICES)
    armario = models.IntegerField(verbose_name="Armário")
    gaveta = models.IntegerField(verbose_name="Gaveta")
    situacao = models.BooleanField(default=True, help_text="Marcado para Ativo. ")
    
    def __str__(self):
        return "{} ({})".format(self.nome, self.matricula)
    
class Movimentacao(models.Model):
    setor = models.CharField(max_length=15, verbose_name="Setor")
    data = models.DateField(default=datetime.date.today)
    
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    
    def __str__(self):
        return "Armário: {}, Gaveta:{} (Setor: {}, Data:{})".format(self.funcionario.armario, self.funcionario.gaveta, self.setor, self.data.strftime('%d/%m/%Y'))

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu usuário'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Digite sua senha'})
    )

cadastros/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from.models import Funcionario,Movimentacao

from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin


class FuncionarioCreate(LoginRequiredMixin ,CreateView):
    login_url = reverse_lazy('login')
    model = Funcionario
    fields = ['nome', 'matricula', 'cpf', 'vinculo', 'armario', 'gaveta', 'situacao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-funcionario')
    
    
    
class MovimentacaoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Movimentacao
    fields = ['setor', 'data', 'funcionario']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-movimentacao')


############ UPDATE ############

class FuncionarioUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Funcionario
    fields = ['nome', 'matricula', 'cpf', 'vinculo', 'armario', 'gaveta', 'situacao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-funcionario')
    
class MovimentacaoUpdate(LoginRequiredMixin, UpdateView):
     login_url = reverse_lazy('login')
     model = Movimentacao
     fields = fields = ['setor', 'data', 'funcionario']
     template_name = 'cadastros/form.html'
     success_url = reverse_lazy('listar-movimentacao')

############ DELETE ############

class FuncionarioDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Funcionario
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-funcionario')

class MovimentacaoDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Movimentacao
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-movimentacao')
    
    
############ LIST ############

class FuncionarioList(ListView):
    model = Funcionario
    template_name = 'cadastros/listas/index.html'
    
    def get_queryset(self):
        
        txt_nome = self.request.GET.get('nome', '')
        
        funcionario = Funcionario.objects.filter(nome__icontains=txt_nome)
        
        return funcionario  
    
class FuncionarioDeleteList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Funcionario
    template_name = 'cadastros/listas/funcionario-delete.html'
    
    def get_queryset(self):
        
        txt_nome = self.request.GET.get('nome', '')
        
        funcionario = Funcionario.objects.filter(nome__icontains=txt_nome)
        
        return funcionario 


class MovimentacaoList(ListView):
    model = Movimentacao
    template_name = 'cadastros/listas/movimentacao.html'
    
     

paginas/views.py
from django.views.generic import TemplateView

# Create your views here.

usuarios/views.py
from django.views.generic.edit import CreateView

cadastros/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% block titulo %}
<title> Excluir | ArchTech</title>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block conteudo %}
<h3>Excluir Registros</h3>
<p class="lead">
    Confirme para excluir o registro definitivamente
</p>
<hr>
<form action="" method="POST">

    <p>
        Deseja excluir o registro: <b>{{ object }}</b>?
    </p>

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Excluir</button>


</form>
{% endblock %}

cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}


{% block titulo %}
<title>Cadastro | ArchTech</title>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block conteudo %}
<h3>Cadastro</h3>
<p class="lead">
    Preencha todos os campos obrigatórios
</p>
<hr>
<div class="row">
    <div class="col-md- mx-auto">
        <form action="" method="POST">

            {% csrf_token %}
        
            {{ form|crispy }}
        
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        
        
        </form>
    </div>
</div>
{% endblock %}

cadastros/templates/cadastros/listas/funcionario-delete.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
<title>Deletar Funcionário | ArchTech</title>
{% endblock %}

{% block conteudo %}
<h3>Lista de campos registrados</h3>
<hr>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Nome</th>
            <th>Matrícula</th>
            <th>CPF</th>
            <th>Vínculo</th>
            <th>Armário</th>
            <th>Gaveta</th>
            <th>Situação</th>
            <th>Opções</th>
        </tr>

        {% for funcionario in object_list %}
        <tr>
            <td>{{ funcionario.nome }}</td>
            <td>{{ funcionario.matricula }}</td>
            <td>{{ funcionario.cpf }}</td>
            <td>{{ funcionario.vinculo }}</td>
            <td>{{ funcionario.armario }}</td>
            <td>{{ funcionario.gaveta }}</td>
            <td>
                {% if funcionario.situacao %}
                    Ativo
                {% else %}
                    Desligado
                {% endif %}
            </td>
            <td>
                <a href="{% url 'excluir-funcionario' funcionario.pk %}" class="btn btn-danger btn-sm" title="Excluir"><i class="fa-solid fa-trash"></i></a>
            </td>
        </tr>

        {% empty %}

        <tr>
            <td colspan="8">Nenhum campo registrado</td>
        </tr>

        {% endfor %}

    </table>
</div>
{% endblock %}

cadastros/templates/cadastros/listas/index.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block titulo %}
<title>Funcionários | ArchTech</title>
{% endblock %}

{% block conteudo %}
<h3>Lista de funcionários registrados</h3>
<hr>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Nome</th>
            <th>Matrícula</th>
            <th>CPF</th>
            <th>Vínculo</th>
            <th>Armário</th>
            <th>Gaveta</th>
            <th>Situação</th>
            <th>Opções</th>
        </tr>

        {% for funcionario in object_list %}
        <tr>
            <td>{{ funcionario.nome }}</td>
            <td>{{ funcionario.matricula }}</td>
            <td>{{ funcionario.cpf }}</td>
            <td>{{ funcionario.get_vinculo_display }}</td>
            <td>{{ funcionario.armario }}</td>
            <td>{{ funcionario.gaveta }}</td>
            <td>
                {% if funcionario.situacao %}
                    Ativo
                {% else %}
                    Desligado
                {% endif %}
            </td>
            <td>
                <a href="{% url 'editar-funcionario' funcionario.pk %}" class="btn btn-warning btn-sm" title="Editar"><i class="fa-solid fa-pen-to-square"></i></a>
                <button class="btn btn-warning btn-sm rastrear-btn" data-nome="{{ funcionario.nome }}" data-setor="{% for movimentacao in funcionario.movimentacao_set.all %}{{ movimentacao.setor }}{% empty %}{% endfor %}"><i class="fa-solid fa-magnifying-glass"></i></button>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="8">Nenhum campo registrado</td>
        </tr>
        {% endfor %}
    </table>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('.rastrear-btn').click(function() {
            var nome = $(this).data('nome');
            var setor = $(this).data('setor');
            
            if (setor) {
                var mensagem = 'A pasta de ' + nome + ' está no setor: ' + setor;
                alert(mensagem);
            } else {
                var mensagem = 'A pasta de ' + nome + ' está no ARQUIVO.';
                alert(mensagem);
            }
        });
    });
</script>
{% endblock %}

cadastros/templates/cadastros/listas/movimentacao.html
{% extends 'paginas/modelo.html' %}
{% load static %}

{% block conteudo %}
<h3>Lista de movimentações registradas</h3>
<hr>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Funcionário</th>
            <th>Amário</th>
            <th>Gaveta</th>
            <th>Setor</th>
            <th>Data</th>
            <th>Opções</th>
        </tr>

        {% for movimentacao in object_list %}
        
        <tr>
            <td>{{ movimentacao.funcionario.nome}}</td>
            <td>{{ movimentacao.funcionario.armario }}</td>
            <td>{{ movimentacao.funcionario.gaveta }}</td>
            <td>{{ movimentacao.setor }}</td>
            <td>{{ movimentacao.data|date }}</td>
            <td>
                <a href="{% url 'excluir-movimentacao' movimentacao.pk %}" class="btn btn-danger btn-sm" title="Rastrear"><i class="fa-solid fa-trash"></i></a>
            </td>
        </tr>

        {% empty %}

        <tr>
            <td colspan="8">Nenhum campo registrado</td>
        </tr>

        {% endfor %}

    </table>
</div>
{% endblock %}

paginas/templates/paginas/cadastrofunc.html
{% extends 'paginas/modelo.html' %}

{% block titulo %}
<title>Arquivo | Cadastrar Funcionário</title>
{% endblock %}

{% block conteudo %}
<h2>This is  a test</h2>
{% endblock %}

paginas/templates/paginas/modelo.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}
    <title>Título</title>
    {% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

</head>
<body>
  <!-- sidebar -->
  <div class="main-container d-flex">
    {% block sidebar %}
    <div class="sidebar" id="side-nav">
      <div class="header-box px-3 pt-3 pb-4">
          <h1 class="fs-4"><img src="{% static 'img/letreiro.png' %}" class="img-fluid pb-4 pt-4 mt-4 mb-4" alt="Home"></h1>
          <button class="btn d-md-none d-block close-btn px-1 py-0 text-white"><i class="fa-solid fa-bars-staggered"></i></button>
          
        <ul class="list-unstyled px-2">
          <li class="active"><a href="{% url 'listar-funcionario' %}" class="text-decoration-none px-3 py-3 d-block"><i class="fa-solid fa-house-user me-2"></i>Página principal</a></li>
          {% if request.user.is_authenticated %}
          <li class=""><a href="{% url 'cadastrar-funcionario' %}" class="text-decoration-none px-3 py-3 d-block"><i class="fa-solid fa-user-plus me-2"></i>Novo Funcionário</a></li>
          <li class=""><a href="{% url 'listar-funcionario-delete' %}"class="text-decoration-none px-3 py-3 d-block"><i class="fa-solid fa-user-xmark me-2"></i>Del. Funcionário</a></li>
          <li class=""><a href="{% url 'cadastrar-movimentacao' %}" class="text-decoration-none px-3 py-3 d-block"><i class="fa-solid fa-folder me-2"></i>Saída pasta</a></li>
          {% endif %}
          <li class=""><a href="{% url 'listar-movimentacao' %}" class="text-decoration-none px-3 py-3 d-block"><i class="fa-solid fa-folder-closed me-2"></i>Movimentações</a></li>
        </ul>
        <hr class="h-color mx-1">
        
        {% if request.user.is_authenticated %}
        <div class="dropdown open">
          <button class="btn border-none dropdown-toggle text-white" type="button" id="triggerId" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
                <i class="fa fa-user"><span class="ms-2">{{ request.user }}</span></i>
              </button>
          <div class="dropdown-menu" aria-labelledby="triggerId">
            <button class="dropdown-item" onclick="logout()">Logout</button>
            <button class="dropdown-item" href="#">Alterar senha</button>
          </div>
        </div>
        {% else %}
        <button class="btn border-none text-white" type="button" id="triggerId" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-user"><a class="btn-login-sidebar" href="{% url 'login' %}">Login</a></i>
        </button>
        {% endif %}

      </div>
    </div>
    {% endblock %}

    <div class="content">
      {% block navbar %}
      <nav class="navbar-nav navbar-light bg-light">
        <div class="container">
          <form action="?" method="GET">
            <div class="d-flex align-items-center">
              <div class="input-group mx-3 my-3">
                <input type="text" class="form-control" placeholder="Nome do Funcionário" aria-label="Recipient's username" aria-describedby="button-addon2" name="nome" value="{{ request.GET.nome }}" autocomplete="off">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Pesquisa</button>
              </div>
              <ul class="navbar-nav ms-3">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}"><i class="fa-solid fa-right-from-bracket fs-3"></i></a>
                </li>
              </ul>
            </div>
          </form> 
        </div>
      </nav>
      {% endblock %}

      <div class="dashboard-content px-3 pt-4 mb-4">
        {% block conteudo %}
        <h2 class="fs-5"> Dashboard Content</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
        {% endblock %}
      </div>
    </div>
  </div>
  <script>
    function logout() {
      window.location.href = "logout/";
    }
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/c70700e259.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

usuarios/templates/usuarios/login.html
{% load static %}



<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/styles-login.css' %}" rel="stylesheet">
    <title>Login | Arquivo Prefeitura </title>
</head>

<body>
    <div class="search">
        <section class="containter-top">
            <img src="{% static 'img/brasao.png' %}" alt="brasão" class="brasao">
            <img src="{% static 'img/LOGO_PMI_SECRATARIAS_BRANCO.png' %}" alt="logo" class="logo">
        </section>

        <section class="containter-bottom">
            <form method="POST" class="form">
                {% csrf_token %}
                <div class="form-control mb-2">
                    {{ form.username }}
                </div>
                <div class="form-control mb-2">
                    {{ form.password }}
                </div>
                <button class="btn-entrar">Entrar</button>
            </form>
        </section>
    </div>

    <footer class="footer">

    </footer>
</body>

</html>